[[main]]
none = "none"

[[main]]
  name = "Articles"
  pageRef = "articles"
  identifier = "TmCySnU7d5"
  weight = 20

[[main]]
  name = "Micro"
  pageRef = "micro"
  weight = 30

[[main]]
  name = "Notes"
  pageRef = "notes"
  weight = 35

[[main]]
  name = "Support"
  url = "https://ko-fi.com/davidwritesxyz"
  weight = 40

[[main]]
  name = "Now"
  pageRef = "Now"
  identifier = "76cUaCSiy6"
  weight = 50

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 60

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/davidwritesxyz"
  weight = 400

[[footer]]
none = "none"
